require('tk.set')
require('tk.plugins')
require('tk.theme')
require('tk.remap')
require('tk.autopairs')
require('tk.lsp')
require('tk.cmp')
require('tk.comment')
-- require('tk.lsp-format')
require('tk.treesitter')
require('tk.luasnip')

